CREATE TABLE `BLOG_BLOGVIEW` (
  `BLOG_ID` int(11) NOT NULL,
  `VIEW` int(11) DEFAULT NULL,
  PRIMARY KEY (`BLOG_ID`),
  KEY `fk_BLOG_BLOGVIEW_1` (`BLOG_ID`),
  CONSTRAINT `fk_BLOG_BLOGVIEW_1` FOREIGN KEY (`BLOG_ID`) REFERENCES `BLOG_BLOGS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


insert into BLOG_BLOGVIEW (blog_id,view) select id,bit from BLOG_BLOGS;