CREATE  TABLE `eyougoblog`.`BLOG_ABOUTS` (
  `ID` VARCHAR(128) NOT NULL ,
  `ABOUTVALUE` TEXT NULL ,
  `BASERANK` INT NULL ,
  PRIMARY KEY (`ID`) )
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;